export enum CommonErrorMessage {
  ALREADY_EXIST = 'Already exist',
  ALREADY_DELETED = 'Already deleted',
  NOT_FOUND = 'Not found',
  INVALID_CATEGORY = 'Invalid category',
  INVALID_EMAIL = 'Invalid email',
  INVALID_PASSWORD = 'Invalid password',
  NOT_MATCH = 'Not match',
  IS_NAN = 'Is not a number',
  IS_WRONG = 'Is wrong',
  PLESASE_TRY_AGAIN = 'Please try again',
  UNAUTHORIZED = 'Unauthorized',
  BAD_TOKEN = 'Bad token',
  TOKEN_EXPIRED = 'Token expired',
  TO_LARGE = 'To large',
  INVALID_FILE_TYPE = 'Invalid file type',
  TIMEOUT = 'Timeout',
  INTERNAL_SERVER_ERROR = 'Internal server error',
}
