version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgressql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src:/usr/src/app
    restart: always
  HEALING_AREA-api:
    build:
      dockerfile: Dockerfile
    container_name: HEALING_AREA-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgresql


