version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgressql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - TZ=Asia/Seoul
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./src:/usr/src/app
    restart: always

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    depends_on:
      - redis


#  HEALING_AREA-api:
#    build:
#      dockerfile: Dockerfile
#    container_name: HEALING_AREA-api
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgresql


